### ISSUE TITLE
VMP Sample Bugg

### ISSUE THREAD

**Issue by hxm-cpp** [struppigel/PortexAnalyzerGUI#1]
![image](https://user-images.githubusercontent.com/116516702/215347433-c38fd421-6818-42b6-814b-0482f81900b6.png)
![image](https://user-images.githubusercontent.com/116516702/215347445-88b7e51c-fca2-42d2-bcfb-b23deddc7375.png)

**Comment by struppigel** [comment]
The export symbol RVAs are in virtual space and therefore not shown. I removed this restriction.
Fixed in release: https://github.com/struppigel/PortexAnalyzerGUI/releases/tag/0.12.8
